### ISSUE TITLE
1000 Listing and export

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#110]
Having a list of 100 with scrolling results in 100 .

**Comment by alakel** [comment]
think of the SQL side paging with DESC order by date

**Comment by DavidBruant** [comment]
As discussed on "burger-at-your-place day", this is hard if not impossible.

To get the *list* of pages for a given **territoire** is gotten as follows:
* get all related **queries**
* get all related **oracle results** (this is a first set of page urls)
* get all **expressions** for these URLs
    * each expression has links (which is a new set of urls)
    * go back to previous step until the set is empty

This is currently done in several (graph depth) back-and-forth from server to database.
Although the order of URLs is maybe deterministic, getting the first 100 makes sense and is easy, but to get from 101 to 200, one has to build the graph from start anyway.

I may end up making a recursive SQL query to build the graph in one go, but that's not a priority.

In any case, when the graph is built, it's sent to the UI and weighs ~1-2MB (100-200k transfered), so that's fast enough. There seems to be a long layout/painting time. But in the right time, it'll be easy to optimize (to give the impression of progressive download).

Closing for now. Let's revisit when we're there.
