### ISSUE TITLE
1000 exports bugs

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#111]
Probably prefer the simple loop writing an xml file that the manufacture of an object that seems too fragile.

**Comment by alakel** [comment]
think of the SQL side paging with DESC order by date

**Comment by DavidBruant** [comment]
Problem here was a performance problem that led to HTTP requests to timeout.
In #114 and https://github.com/DavidBruant/MyWebIntelligence/commit/b321f6c05efdf2aef18e9a49b59278bccad980ec specifically, it was found (and fixed) that code that exported the graph from the database to the front end had quadratic behavior.

This has been fixed mostly.
It's possible a problem remains when turning a page graph into a domain graph because this code uses nested `Map` (which is currently a polyfill with linear lookup). We'll see if that becomes a problem before moving to a version of Node with native Maps.
