### ISSUE TITLE
CrawlLiens

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#152]

**Comment by DavidBruant** [comment]
This is a followup to #13. #13 exact purpose was to:
* get a webpage content
* extract title, meta description, etc.
* extract the main content (readability)
* (soon isolate summary #147 )

This issue aims at re-enabling crawling. This issue is intertwined with #19 #133.
"Graph Cleaning" and "Approval" are the same thing.
