### ISSUE TITLE
DomainExpression Tag by Meta Title, description and keywords

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#192]
The use of this kind of service shows that meta are generally well documented and allow to identifie clairly the domain of expression. 
http://tools.buzzstream.com/meta-tag-extractor
can we have easily this kind of routine ?

**Comment by DavidBruant** [comment]
Don't we already do that?
https://github.com/MyWebIntelligence/MyWebIntelligence/blob/70a3899f9954e92aa80ade4d506932ae809a3b12/crawl/makeResourceInfo.js#L54-L55

We already discussed about `keywords` and decided to go along the practice of search engines which is to ignore them because they're either undocumented or likely spammy and uninformative.
What changed?
That `keywords` are useless is so widely acknowledged that there is even [a note in the HTML spec about that](https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names)

In related news, on my own time, I [played around with ElasticSearch](https://github.com/DavidBruant/elastic-playground) and extracting the most frequent stems of a text (words alone with custom list of stop words or 2-3-4-5-grams) turns out to be a trivial task and is now a solved problem (as anticipated ;-) ).
It's unclear whether meta keywords are at all meaningful in comparison.

**Comment by DavidBruant** [comment]
For reference, analysis of the [English X-men Wikipedia page](https://en.wikipedia.org/wiki/X-Men): https://gist.github.com/DavidBruant/8a5ff5a9e65f932c29b7

**Comment by alakel** [comment]
Don't we already do that? 
No we need for the node (and not the page), the meta of the main page (the home page in the most frequent case)

What changed?
The test i do with buzzstream (see above) and when you test html meta, twitter, facebook and google plus cards...you discovers that you fnd always title, description and meta.

This meta are very important because its the will of rea author for annotating his Node and their pageS. We have to try everything to  read it. and yes it's not perfect, like reality ;-)

**Comment by alakel** [comment]
WHOOOOAOOOOOOUUUUUUUUUU Elastic search N-Gram ! Yes we always dream about it....but i dont believe it since i saw it....YES...the hope that show your test it very very hopeful and enthousiamic !....OMG...

**Comment by DavidBruant** [comment]
Done at https://github.com/MyWebIntelligence/MyWebIntelligence/pull/197
