### ISSUE TITLE
Modify titles and descriptions on list domain (for bugs fixing) by double click and exit

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#290]

**Comment by DavidBruant** [comment]
IIRC we had a discussion about this which went pretty much like this:
* `title` and `description` and [expression_domain attributes](https://github.com/MyWebIntelligence/MyWebIntelligence/blob/b19fc045352836bcacf0e3b05fe502f437c8ac76/database/management/createTables.sql#L161-L162) (not annotations), so modifying them once would mean modifying them in one territoire means for all territoires
* It doesn't really make sense to make them annotations because they're not really annotations
* It seems that the bigger problem is that title and description were not properly fetched because of another problem (see #245 ), so this should be much less of a problem now.

Closing accordingly.
